version: '3.7'

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - "${RUNNING_PORT}:${RUNNING_PORT}"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${RUNNING_PORT}" ]
